### ISSUE TITLE
Player doesn't collide evenly in corners of the map

### ISSUE THREAD

**Issue by Ashe** [rake146/Game#1]
![screenshot 2017-04-16 23 11 12](https://cloud.githubusercontent.com/assets/8940077/25074715/03e1a2ae-22fa-11e7-90a2-49a516b2864d.png)

***vs***

![screenshot 2017-04-16 23 11 36](https://cloud.githubusercontent.com/assets/8940077/25074716/0c894a24-22fa-11e7-8a67-57c79d864ef2.png)

**Comment by rake146** [comment]
I have now fixed all collisions with the walls.
